import { SignToken } from "../types/sign";

export const availableSignTokens: SignToken[] = [
  "HELLO",
  "THANK_YOU",
  "HELP",
  "WATER",
  "YES",
  "NO",
  "BATHROOM",
  "DOCTOR",
  "PAIN",
  "STOP",
  "WAIT",
  "WRITE",
  "CALL",
  "WHERE",
  "NOW",
  "PLEASE",
  "FOOD",
  "EAT",
  "MORE",
  "AGAIN",
  "SORRY",
  "GOOD",
  "BAD",
  "NAME",
  "WHAT",
  "WHO",
  "WHY",
  "HOW",
  "WHEN",
  "HOME",
  "SCHOOL",
  "WORK",
  "FAMILY",
  "MOTHER",
  "FATHER",
  "FRIEND",
  "TEACHER",
  "STUDENT",
  "LEARN",
  "UNDERSTAND",
  "SICK",
  "MEDICINE",
  "HOSPITAL",
  "GO",
  "COME",
  "WANT",
  "NEED",
  "LIKE",
  "HAPPY",
  "SAD"
];

export const phase2TargetSignTokens = [
  "BATHROOM",
  "DOCTOR",
  "PAIN",
  "STOP",
  "WAIT",
  "WRITE",
  "CALL",
  "WHERE",
  "NOW",
  "PLEASE",
  "FOOD",
  "EAT",
  "MORE",
  "AGAIN",
  "SORRY",
  "GOOD",
  "BAD",
  "NAME",
  "WHAT",
  "WHO",
  "WHY",
  "HOW",
  "WHEN",
  "HOME",
  "SCHOOL",
  "WORK",
  "FAMILY",
  "MOTHER",
  "FATHER",
  "FRIEND",
  "TEACHER",
  "STUDENT",
  "LEARN",
  "UNDERSTAND",
  "SICK",
  "MEDICINE",
  "HOSPITAL",
  "GO",
  "COME",
  "WANT",
  "NEED",
  "LIKE",
  "HAPPY",
  "SAD"
] as const satisfies readonly SignToken[];

export type Phase2TargetSignToken = (typeof phase2TargetSignTokens)[number];

export type SignTokenCategory = "starter" | "needs" | "medical" | "conversation" | "places" | "questions" | "people" | "school";

export const signTokenCategories: Record<SignTokenCategory, SignToken[]> = {
  conversation: ["PLEASE", "THANK_YOU", "YES", "NO", "WAIT", "STOP", "WRITE", "AGAIN", "SORRY", "GOOD", "BAD"],
  medical: ["DOCTOR", "PAIN", "SICK", "MEDICINE", "HOSPITAL"],
  needs: ["HELP", "WATER", "BATHROOM", "CALL", "NOW", "FOOD", "EAT", "MORE", "WANT", "NEED"],
  people: ["FAMILY", "MOTHER", "FATHER", "FRIEND", "TEACHER", "STUDENT"],
  places: ["WHERE", "HOME", "SCHOOL", "WORK", "GO", "COME"],
  questions: ["WHAT", "WHO", "WHY", "HOW", "WHEN", "NAME"],
  school: ["SCHOOL", "TEACHER", "STUDENT", "LEARN", "UNDERSTAND", "WRITE"],
  starter: ["HELLO", "THANK_YOU", "HELP", "WATER", "YES", "NO"]
};

export const signTokenCategoryLabels: Record<SignTokenCategory, string> = {
  conversation: "Conversation",
  medical: "Medical",
  needs: "Needs",
  people: "People",
  places: "Places",
  questions: "Questions",
  school: "School",
  starter: "Starter"
};

export const phase2VocabularyNotes: Record<Phase2TargetSignToken, string> = {
  BATHROOM: "High-value public navigation intent.",
  CALL: "Emergency and caregiver communication.",
  DOCTOR: "Medical environment intent.",
  AGAIN: "Conversation repair intent.",
  BAD: "Basic opinion and status intent.",
  COME: "Movement and caregiver direction intent.",
  EAT: "Restaurant and basic need action.",
  FAMILY: "Personal context and caregiver vocabulary.",
  FATHER: "Family and caregiver vocabulary.",
  FOOD: "Restaurant and basic need intent.",
  FRIEND: "People and support vocabulary.",
  GO: "Movement and destination intent.",
  GOOD: "Basic opinion and status intent.",
  HAPPY: "Emotion vocabulary.",
  HOME: "Common place and safety destination.",
  HOSPITAL: "Medical navigation and emergency intent.",
  HOW: "Question vocabulary.",
  LEARN: "School and communication repair intent.",
  LIKE: "Preference vocabulary.",
  MEDICINE: "Medical need intent.",
  MORE: "Basic request modifier.",
  MOTHER: "Family and caregiver vocabulary.",
  NAME: "Introduction and identity vocabulary.",
  NEED: "Core request intent.",
  NOW: "Timing modifier for urgent requests.",
  PAIN: "Medical and emergency intent.",
  PLEASE: "Politeness modifier for phrase composition.",
  SAD: "Emotion vocabulary.",
  SCHOOL: "Common environment vocabulary.",
  SICK: "Medical status intent.",
  SORRY: "Social repair vocabulary.",
  STOP: "Safety and boundary intent.",
  STUDENT: "School and identity vocabulary.",
  TEACHER: "School and people vocabulary.",
  UNDERSTAND: "Conversation repair intent.",
  WAIT: "Conversation pacing intent.",
  WANT: "Core request intent.",
  WHAT: "Question vocabulary.",
  WHEN: "Question vocabulary.",
  WHERE: "Question modifier for navigation.",
  WHO: "Question vocabulary.",
  WHY: "Question vocabulary.",
  WORK: "Common place and routine vocabulary.",
  WRITE: "Conversation repair and accessibility intent."
};
